# Numpy

- Numpy is a general purpose array processing package.
- Numpy was created to work with multidimensional arrays.
- It is the fundamental package for scientific computing with python.
- It is open source library.

**Why use Numpy?**

- In python we have list that serves the purpose of arrays, but they are slow in process.
- Numpy aims to provide an array object that is upto 50x faster than traditonal python lists.
- The array object in numpy is called ndarray, it provides a lot of supporting functions that 
  make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.  

In [4]:
#Importing necessary library
!pip install numpy
import numpy as np

In [7]:
#Array creation
a = np.array(10)
type(a)

numpy.ndarray

In [8]:
#Zero dimensional array

In [18]:
z = np.array(5)
z.ndim

0

In [13]:
#One dimensional array

In [15]:
o = np.array([10,56,45,39])
o.ndim

1

In [19]:
#Two dimensional array

In [21]:
t = np.array([[10,56,45,34]])
t.ndim

2

In [22]:
#Three dimensional array

In [24]:
d = np.array([[[46,34,78,10]]])
d.ndim

3

In [25]:
#Change the datatype of the array elements

In [29]:
a = np.array([10,40,30,20])
a.dtype

dtype('int32')

In [27]:
a = np.array([10,40,30,20], dtype = 'float')
print(a.dtype)
a

float64


array([10., 40., 30., 20.])

# Other ways of creating an array

1. arange
2. linspace
3. zeros
4. ones
5. random

In [ ]:
#arange

In [31]:
a = np.arange(1,21,2)
a           #start,stop,step

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#linspace

In [33]:
b = np.linspace(1,8,15, retstep = True)      #retstep will show the difference between two values
b

(array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
        7.5, 8. ]),
 0.5)

In [34]:
#Zeros

In [36]:
z = np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [37]:
#Ones

In [39]:
o = np.ones([4,4])
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
#random

In [41]:
r = np.random.rand(5,2)
r

array([[0.12527226, 0.03416618],
       [0.3761874 , 0.4061012 ],
       [0.1163049 , 0.45213311],
       [0.32836502, 0.81190743],
       [0.34493741, 0.4492669 ]])

In [43]:
r = np.random.randint(5,size = 10)   #Return random integers from low(inclusive) to high(exclusive)
r

array([1, 4, 2, 3, 1, 2, 1, 2, 0, 1])

# Slicing and indexing of arrays

In [45]:
s = np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
# 1
s[0,0]

1

In [49]:
# 6 
s[1,2]

6

In [50]:
# 2 and 3
s[0,1:]

array([2, 3])

In [51]:
# 2,3 and 5,6
s[0:,1:]

array([[2, 3],
       [5, 6]])

In [52]:
# 1 and 6
s[[0,1],[0,2]]

array([1, 6])

In [54]:
# 3 and 4
s[[0,1],[2,0]]

array([3, 4])

# Reshaping the array

In [56]:
r = np.random.rand(5,2)
r

array([[0.47253555, 0.76961395],
       [0.31053768, 0.75085584],
       [0.36650025, 0.78966292],
       [0.24122576, 0.55465967],
       [0.4139251 , 0.38260344]])

In [58]:
r.reshape(2,5)

array([[0.47253555, 0.76961395, 0.31053768, 0.75085584, 0.36650025],
       [0.78966292, 0.24122576, 0.55465967, 0.4139251 , 0.38260344]])

In [60]:
r.reshape(10,1)

array([[0.47253555],
       [0.76961395],
       [0.31053768],
       [0.75085584],
       [0.36650025],
       [0.78966292],
       [0.24122576],
       [0.55465967],
       [0.4139251 ],
       [0.38260344]])

In [62]:
r.reshape(1,10)

array([[0.47253555, 0.76961395, 0.31053768, 0.75085584, 0.36650025,
        0.78966292, 0.24122576, 0.55465967, 0.4139251 , 0.38260344]])

In [64]:
r.reshape(5,-1)

array([[0.47253555, 0.76961395],
       [0.31053768, 0.75085584],
       [0.36650025, 0.78966292],
       [0.24122576, 0.55465967],
       [0.4139251 , 0.38260344]])

# Aggregate function

- The python numpy aggregate functions are sum, min, max, mean, average, product, median, standard 
  deviation, variance, percentile, and corelation coefficent

In [65]:
r.min()

0.2412257578230046

In [67]:
r.max()

0.7896629186276896

In [69]:
r.mean()

0.5052120144118507

In [71]:
r.std()

0.19101527901298246

In [72]:
r.var()

0.03648683681640754

# Stacking

- Stacking is used to join two different array
- Vertical stacking
- Horizontal stacking

In [75]:
a = np.array([1,23,43,2])
b = np.array([2,45,67,23])

In [77]:
np.hstack([a,b])

array([ 1, 23, 43,  2,  2, 45, 67, 23])

In [78]:
np.vstack([a,b])

array([[ 1, 23, 43,  2],
       [ 2, 45, 67, 23]])